# Generated by Django 4.2 on 2023-12-26 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Sum_Scores', models.FloatField(default=0, editable=False)),
                ('Count_Scores', models.FloatField(default=0, editable=False)),
                ('Average_Score', models.FloatField(default=0, editable=False)),
                ('Code', models.CharField(max_length=6, unique=True)),
                ('Phone_number', models.CharField(max_length=11)),
                ('Visit_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Age', models.PositiveIntegerField()),
                ('National_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Bimar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Specialty.patient')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Specialty.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='Specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Specialty.speciality'),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=100)),
                ('Comment', models.TextField()),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Specialty.doctor')),
            ],
        ),
    ]
