# Generated by Django 4.2 on 2023-12-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Specialty', '0003_reserve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='Date',
            field=models.DateField(),
        ),
    ]
