# Generated by Django 4.2 on 2023-12-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Specialty', '0004_alter_reserve_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='Bimar',
            new_name='bimar',
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='Doctor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='Time',
            new_name='time',
        ),
    ]
