# Generated by Django 4.2 on 2023-12-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Specialty', '0005_rename_bimar_reserve_bimar_rename_date_reserve_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Doctor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='User',
            new_name='user',
        ),
    ]
