# Generated by Django 4.2 on 2023-12-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Specialty', '0006_rename_comment_comment_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='National_id',
            new_name='national_id',
        ),
    ]
