# Generated by Django 4.2 on 2023-12-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Specialty', '0007_doctor_average_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='Phone_number',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='Visit_cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
