# Generated by Django 4.2 on 2023-12-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Specialty', '0007_rename_age_patient_age_rename_name_patient_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Average_Score',
            new_name='average_Score',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Count_Scores',
            new_name='count_Scores',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Specialty',
            new_name='specialty',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Sum_Scores',
            new_name='sum_Scores',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Visit_cost',
            new_name='visit_cost',
        ),
    ]
