# Generated by Django 4.2 on 2023-12-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Specialty', '0008_doctor_code_doctor_phone_number_doctor_visit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
