# Generated by Django 4.2 on 2023-12-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Specialty', '0008_rename_average_score_doctor_average_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciality',
            old_name='Name',
            new_name='name',
        ),
    ]
