# Generated by Django 4.2 on 2023-12-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply',
            new_name='ticket',
        ),
    ]
